class AddLoseFatAndToneToUser < ActiveRecord::Migration
  def change
    add_column :users, :lose_fat_and_tone, :string
    add_column :users, :better_my_endurance, :string
    add_column :users, :get_stronger, :string
    add_column :users, :connect_my_mind_and_body, :string
    add_column :users, :eat_better, :string
    add_column :users, :units, :string
    add_column :users, :weight, :integer
    add_column :users, :height, :integer
    add_column :users, :birthday, :date
    add_column :users, :doctor_clearance, :boolean
    add_column :users, :currently_pregnant, :boolean
    add_column :users, :heart_condition, :boolean
    add_column :users, :shortness_breath, :boolean
    add_column :users, :unusual_fatigue, :boolean
    add_column :users, :coronary_heart_disease, :boolean
    add_column :users, :high_pressure, :boolean
    add_column :users, :stroke, :boolean
    add_column :users, :diabetes, :boolean
    add_column :users, :thyroid_problems, :boolean
    add_column :users, :head_injury_epilepsy, :boolean
    add_column :users, :hepatitis, :boolean
    add_column :users, :arthritis, :boolean
    add_column :users, :chronic_severe_headaches, :boolean
    add_column :users, :anemia, :boolean
    add_column :users, :liver_problems, :boolean
    add_column :users, :lung_problems, :boolean
    add_column :users, :others, :boolean
    add_column :users, :no, :boolean
    add_column :users, :contact_time_window, :string
    add_column :users, :contact_phone_number, :string
    add_column :users, :own_roku, :boolean
    add_column :users, :first_name, :string
    add_column :users, :last_name, :string
    add_column :users, :address_line_1, :string
    add_column :users, :address_line_2, :string
    add_column :users, :city, :string
    add_column :users, :state, :string
    add_column :users, :zip, :integer
    add_column :users, :country, :string
    add_column :users, :reg_phone, :string
    add_column :users, :plan_1_monthly, :boolean
    add_column :users, :plan_1_trimonthly, :boolean
    add_column :users, :plan_2_monthly, :boolean
    add_column :users, :plan2_trimonthly, :boolean
    add_column :users, :card_type, :string
    add_column :users, :card_number, :string
    add_column :users, :exp_month, :integer
    add_column :users, :exp_year, :integer
    add_column :users, :cvv, :integer
    add_column :users, :discount_code, :string
    add_column :users, :billing_first_name, :string
    add_column :users, :billing_last_name, :string
    add_column :users, :billing_address_1, :string
    add_column :users, :billing_address_2, :string
    add_column :users, :billing_city, :string
    add_column :users, :billing_state, :string
    add_column :users, :billing_zip, :integer
    add_column :users, :billing_country, :string
    add_column :users, :billing_phone, :string
  end
end